name: compiling

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: fetch
        uses: actions/checkout@v1
      - name: run
        run: |
          mkdir build
          cd build
          cmake ..
          make
